/**
 * Generated identity marks for brand and gear sets.
 *
 * The real in-game logos are Ubisoft's and are not safe to ship, so each set
 * gets a monogram derived from its name, tinted by what the set's own bonus
 * lines actually do. Nothing here is hand-entered: both the monogram and the
 * tone are computed from `data/`, so a regenerated data file produces
 * regenerated marks.
 *
 * This lives in `lib/` rather than `data/` on purpose. `data/` is machine-
 * generated by `scripts/build-data.mjs` and is overwritten wholesale on every
 * run, which would clobber anything added alongside it.
 */

import { BRANDS } from "@/data/brands";
import { GEAR_SETS } from "@/data/gearSets";
import type { Brand, GearSet } from "@/lib/types";

export type MarkTone = "offensive" | "defensive" | "skill";

export interface IdentityMark {
  readonly monogram: string;
  readonly tone: MarkTone;
}

/* ---- tone ------------------------------------------------------------ */

/*
 * Order matters. A bonus line is scored against all three vocabularies and the
 * highest count wins, but skill terms are checked as whole phrases first:
 * "Skill Damage" and "Repair Skills" are skill lines, not offensive ones,
 * even though they contain "Damage" and would otherwise score as weapon stats.
 */
const SKILL =
  /skill (?:haste|damage|duration|efficiency|health|tier)|repair[- ]skills?|status effects?|shield health|burn duration/gi;

const DEFENSIVE =
  /armor|health|hazard protection|protection from elites|threat|regen|resistance/gi;

const OFFENSIVE =
  /damage|critical|headshot|handling|magazine|mag size|reload|accuracy|stability|rate of fire|optimal range|ammo capacity|rifle|smg|lmg|shotgun|pistol|mmr/gi;

const count = (line: string, re: RegExp): number =>
  (line.match(re) ?? []).length;

/** Null for a line that matches no vocabulary, so it abstains rather than voting. */
const classifyLine = (line: string): MarkTone | null => {
  const skill = count(line, SKILL);
  if (skill > 0) return "skill";

  const offensive = count(line, OFFENSIVE);
  const defensive = count(line, DEFENSIVE);
  if (offensive === 0 && defensive === 0) return null;
  return offensive >= defensive ? "offensive" : "defensive";
};

/** Majority vote across a set's own bonus lines; offensive breaks a tie. */
const toneFor = (lines: readonly string[]): MarkTone => {
  const tally: Record<MarkTone, number> = {
    offensive: 0,
    defensive: 0,
    skill: 0,
  };

  for (const line of lines) {
    const tone = classifyLine(line);
    if (tone) tally[tone] += 1;
  }

  const order: readonly MarkTone[] = ["offensive", "defensive", "skill"];
  return order.reduce((best, tone) =>
    tally[tone] > tally[best] ? tone : best,
  );
};

/* ---- monogram -------------------------------------------------------- */

/** Legal forms and joining words carry no identity, so they never start a monogram. */
const NOISE = new Set([
  "sro", "sa", "spa", "ltd", "gmbh", "ab", "inc", "co", "corp",
  "corporation", "sp", "z", "oo", "and", "of", "the", "de", "&",
]);

const monogramFor = (name: string): string => {
  const words = name
    .split(/[\s,:]+/)
    .map((w) => w.replace(/[^\p{L}\p{N}.]/gu, ""))
    .filter(Boolean)
    .filter((w) => !NOISE.has(w.replace(/\./g, "").toLowerCase()));

  const initials = words.slice(0, 2).map((w) => w[0]);
  return initials.join("").toLocaleUpperCase();
};

/* ---- assembly -------------------------------------------------------- */

const brandLines = (brand: Brand): string[] =>
  brand.bonuses.filter((b): b is string => Boolean(b));

const gearSetLines = (set: GearSet): string[] => [
  ...set.bonus2pc,
  ...set.bonus3pc,
];

const markFrom = (name: string, lines: readonly string[]): IdentityMark => ({
  monogram: monogramFor(name),
  tone: toneFor(lines),
});

export const BRAND_MARKS: ReadonlyMap<string, IdentityMark> = new Map(
  BRANDS.map((b) => [b.id, markFrom(b.name, brandLines(b))]),
);

export const GEAR_SET_MARKS: ReadonlyMap<string, IdentityMark> = new Map(
  GEAR_SETS.map((g) => [g.id, markFrom(g.name, gearSetLines(g))]),
);

/** Across all brand and gear sets, for sanity-checking a data regeneration. */
export const toneDistribution = (): Record<MarkTone, number> => {
  const dist: Record<MarkTone, number> = {
    offensive: 0,
    defensive: 0,
    skill: 0,
  };
  for (const mark of [...BRAND_MARKS.values(), ...GEAR_SET_MARKS.values()]) {
    dist[mark.tone] += 1;
  }
  return dist;
};
